#!/bin/bash

# Define paths for cron environment






PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

process=${1:-httpd}
current_time=$(date '+%Y-%m-%d_%H-%M-%S')

if ! systemctl is-active -q "$process"; then
    echo "Warning service is down! Attempting to restart..."
    systemctl start "$process"
    echo "Warning, the server is down." | mail -s "Critical" your-email@gmail.com
else
    echo "$process is running $current_time" >> /home/log.txt
fi
